#!/bin/bash
APPSNAME="DomoApps"
SERV=".service"
ETCDIR="/etc"
SERVICEDIR="$ETCDIR/systemd/system"
APPSSERVICESCRIPT="$APPSNAME""$SERV"

echo "Uninstalling finished, try restarting $APPSNAME service"
if [ -f "$SERVICEDIR/$APPSSERVICESCRIPT" ]; then
    systemctl stop $APPSSERVICESCRIPT
    systemctl start $APPSSERVICESCRIPT
fi

exit 0
