#!/bin/bash
SERVICENAME="Domo_app_weather"
SERV=".service"
ETCDIR="/etc"
SERVICEDIR="$ETCDIR/systemd/system"
SERVICESCRIPT="$SERVICENAME""$SERV"
OPTDIR="/opt"
OPTLOC="$OPTDIR/$SERVICENAME"

echo "Installing decentralized common folder"
COMMONLOC="$OPTLOC""/appcommon"
if [ ! -d "$COMMONLOC" ]; then
    mkdir "$COMMONLOC"
    chmod 755 "$COMMONLOC"
fi

CURLOC=$(pwd)
cd $COMMONLOC
wget https://raw.githubusercontent.com/Helly1206/Domotion/master/apps/appcommon/appcommon.py
wget https://raw.githubusercontent.com/Helly1206/Domotion/master/apps/appcommon/bdaclient.py
wget https://raw.githubusercontent.com/Helly1206/Domotion/master/apps/appcommon/bdauri.py
cd $CURLOC

echo "Install automatic startup service for $SERVICENAME"

systemctl enable $SERVICESCRIPT
systemctl start $SERVICESCRIPT

exit 0
